In [14]:
import pandas as pd
from warnings import filterwarnings
filterwarnings("ignore")

# pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

## 1. Load schedule JSON

- This JSON file is generated by 

Take whatever is inside each cell of df['persona'] and expand it into separate columns.

In [15]:
seed_persona = pd.read_json('../app/src/smallville_personas.json')
gemini_json = pd.read_json('../app/src/driftville_personas_model_comparisons/driftville_personas_v8_gemini-3-flash-preview:cloud.json')
gemini_json

json_persona = pd.read_json('../app/src/driftville_personas.json')
json_persona

json_persona == gemini_json

    persona  schedule
0      True      True
1      True      True
2      True      True
3      True      True
4      True      True
5      True      True
6      True      True
7      True      True
8      True      True
9      True      True
10     True      True
11     True      True

Above, we just confimred that the final `driftville_personas.json` was generated by **Gemini 3 Flash Preview** model.

In [16]:
# clean the raw persona text
seed_persona['raw_persona'] = seed_persona['raw_persona'].apply(lambda x: x.replace('\n', ' '))
seed_persona

                  name                                        raw_persona
0   Isabella Rodriguez  Basic information First name Isabella Last nam...
1           Tom Moreno  Basic information First name Tom Last name Mor...
2        Giorgio Rossi  Basic information First name Giorgio Last name...
3           Adam Smith  Basic information First name Adam Last name Sm...
4            Sam Moore  Basic information First name Sam Last name Moo...
5          Maria Lopez  Basic information First name Maria Last name L...
6              Mei Lin  Basic information First name Mei Last name Lin...
7       Jennifer Moore  Basic information First name Jennifer Last nam...
8       Hailey Johnson  Basic information First name Hailey Last name ...
9             Eddy Lin  Basic information First name Eddy Last name Li...
10            John Lin  Basic information First name John Last name Li...
11        Abigail Chen  Basic information First name Abigail Last name...

In [17]:
# Merge seed persona and generated json persona to compare 
# seed_person + JSON (persona)
merged = pd.merge(seed_persona, json_persona['persona'].apply(pd.Series), left_on='name', right_on='name', how='outer')
# seed_person + JSON (persona) + JSON (schedule)
merged = pd.concat([merged, json_persona.explode('schedule').apply(pd.Series)['schedule'].apply(pd.Series)], axis=1)
print(merged.shape)
merged.tail()

(141, 14)

,name,raw_persona,occupation,relationship,innate_tendency,learned_tendency,current_situation,lifestyle,datetime_start,duration_min,location,action,environment_description,notes
11,Tom Moreno,Basic information First name Tom Last name Mor...,Grocery Shop Keeper,"{'name': 'Jane Moreno', 'relation_type': 'part...","[rude, aggressive, energetic]",Tom Moreno is a grocery shop keeper at The Wil...,Tom is managing the store and helping customer...,"Tom Moreno goes to bed around 11pm, awakes up ...",2023-02-13 18:00,60,running_trail,jogging,"thud of feet on the trail, chirping birds, coo...",Evening jog to stay active.
11,Tom Moreno,Basic information First name Tom Last name Mor...,Grocery Shop Keeper,"{'name': 'Jane Moreno', 'relation_type': 'part...","[rude, aggressive, energetic]",Tom Moreno is a grocery shop keeper at The Wil...,Tom is managing the store and helping customer...,"Tom Moreno goes to bed around 11pm, awakes up ...",2023-02-13 19:00,60,home:kitchen,dinner,"clinking of silverware, scent of pasta, phone ...",Enjoying dinner while thinking about interacti...
11,Tom Moreno,Basic information First name Tom Last name Mor...,Grocery Shop Keeper,"{'name': 'Jane Moreno', 'relation_type': 'part...","[rude, aggressive, energetic]",Tom Moreno is a grocery shop keeper at The Wil...,Tom is managing the store and helping customer...,"Tom Moreno goes to bed around 11pm, awakes up ...",2023-02-13 20:00,60,home:living_room,watch_tv,"flicker of the TV screen, sound of a documenta...",Watching TV for inspiration.
11,Tom Moreno,Basic information First name Tom Last name Mor...,Grocery Shop Keeper,"{'name': 'Jane Moreno', 'relation_type': 'part...","[rude, aggressive, energetic]",Tom Moreno is a grocery shop keeper at The Wil...,Tom is managing the store and helping customer...,"Tom Moreno goes to bed around 11pm, awakes up ...",2023-02-13 21:00,120,home:studio,creative_work,"hum of the computer, clicking of the stylus, p...",Experimenting with new tools and techniques.
11,Tom Moreno,Basic information First name Tom Last name Mor...,Grocery Shop Keeper,"{'name': 'Jane Moreno', 'relation_type': 'part...","[rude, aggressive, energetic]",Tom Moreno is a grocery shop keeper at The Wil...,Tom is managing the store and helping customer...,"Tom Moreno goes to bed around 11pm, awakes up ...",2023-02-13 23:00,60,home:bathroom,night_routine,"running water, scent of face wash, soft towel,...",Preparing for bed.

## Export merged to CSV

- smallville persona seed(JSON) + driftville persona/scheudle (JSON)

In [18]:
merged.to_csv('../app/src/merged_driftville_persona.csv', index=False)

## Filter by persona

In [19]:
# select persona
selected_persona = "isabella"
selected_persona_df = merged[merged["name"].str.contains(selected_persona, case=False, na=False)]
print(selected_persona_df.shape)
selected_persona_df

(10, 14)

,name,raw_persona,occupation,relationship,innate_tendency,learned_tendency,current_situation,lifestyle,datetime_start,duration_min,location,action,environment_description,notes
5,Isabella Rodriguez,Basic information First name Isabella Last nam...,Cafe Owner,"{'name': 'Maria Lopez', 'relation_type': 'frie...","[friendly, outgoing, hospitable]",Isabella Rodriguez is a cafe owner of Hobbs Ca...,Isabella is planning a Valentine's Day party a...,"Isabella Rodriguez goes to bed around 11pm, aw...",2023-02-13 00:00,600,home:bedroom,sleep,"faint hum of a computer, darkness, soft rustle...",Sleeping in after a late night stream.
5,Isabella Rodriguez,Basic information First name Isabella Last nam...,Cafe Owner,"{'name': 'Maria Lopez', 'relation_type': 'frie...","[friendly, outgoing, hospitable]",Isabella Rodriguez is a cafe owner of Hobbs Ca...,Isabella is planning a Valentine's Day party a...,"Isabella Rodriguez goes to bed around 11pm, aw...",2023-02-13 10:00,60,home:bathroom,morning_routine,"splashing water, scent of citrus body wash, ph...",Maria wakes up feeling energetic.
5,Isabella Rodriguez,Basic information First name Isabella Last nam...,Cafe Owner,"{'name': 'Maria Lopez', 'relation_type': 'frie...","[friendly, outgoing, hospitable]",Isabella Rodriguez is a cafe owner of Hobbs Ca...,Isabella is planning a Valentine's Day party a...,"Isabella Rodriguez goes to bed around 11pm, aw...",2023-02-13 11:00,60,Oak_Hill_College:library,study,"whispered conversations, rustle of papers, pho...",Studying physics and participating in online d...
5,Isabella Rodriguez,Basic information First name Isabella Last nam...,Cafe Owner,"{'name': 'Maria Lopez', 'relation_type': 'frie...","[friendly, outgoing, hospitable]",Isabella Rodriguez is a cafe owner of Hobbs Ca...,Isabella is planning a Valentine's Day party a...,"Isabella Rodriguez goes to bed around 11pm, aw...",2023-02-13 12:00,60,Hobbs_Cafe:main_floor,lunch,"clinking of mugs, aroma of coffee, background ...",Lunch at her favorite cafe while catching up o...
5,Isabella Rodriguez,Basic information First name Isabella Last nam...,Cafe Owner,"{'name': 'Maria Lopez', 'relation_type': 'frie...","[friendly, outgoing, hospitable]",Isabella Rodriguez is a cafe owner of Hobbs Ca...,Isabella is planning a Valentine's Day party a...,"Isabella Rodriguez goes to bed around 11pm, aw...",2023-02-13 13:00,60,rock_climbing_gym,rock_climbing,"thud of feet on mats, scent of chalk, sound of...",One hour of intense physical activity.
5,Isabella Rodriguez,Basic information First name Isabella Last nam...,Cafe Owner,"{'name': 'Maria Lopez', 'relation_type': 'frie...","[friendly, outgoing, hospitable]",Isabella Rodriguez is a cafe owner of Hobbs Ca...,Isabella is planning a Valentine's Day party a...,"Isabella Rodriguez goes to bed around 11pm, aw...",2023-02-13 14:00,240,home:twitch_streaming_room,twitch_stream,"glow of multiple monitors, clicking of a mecha...",Streaming games and interacting with her audie...
5,Isabella Rodriguez,Basic information First name Isabella Last nam...,Cafe Owner,"{'name': 'Maria Lopez', 'relation_type': 'frie...","[friendly, outgoing, hospitable]",Isabella Rodriguez is a cafe owner of Hobbs Ca...,Isabella is planning a Valentine's Day party a...,"Isabella Rodriguez goes to bed around 11pm, aw...",2023-02-13 18:00,60,home:living_room,relax,"soft evening light, quiet hum of the house, ph...",Decompressing after the stream.
5,Isabella Rodriguez,Basic information First name Isabella Last nam...,Cafe Owner,"{'name': 'Maria Lopez', 'relation_type': 'frie...","[friendly, outgoing, hospitable]",Isabella Rodriguez is a cafe owner of Hobbs Ca...,Isabella is planning a Valentine's Day party a...,"Isabella Rodriguez goes to bed around 11pm, aw...",2023-02-13 19:00,120,home:kitchen,dinner,"clinking of silverware, scent of spicy food, p...",Enjoying dinner while checking her stream stats.
5,Isabella Rodriguez,Basic information First name Isabella Last nam...,Cafe Owner,"{'name': 'Maria Lopez', 'relation_type': 'frie...","[friendly, outgoing, hospitable]",Isabella Rodriguez is a cafe owner of Hobbs Ca...,Isabella is planning a Valentine's Day party a...,"Isabella Rodriguez goes to bed around 11pm, aw...",2023-02-13 21:00,120,home:living_room,socialize,"laughter, sound of a video game in the backgro...",Talking to friends online or in person.
5,Isabella Rodriguez,Basic information First name Isabella Last nam...,Cafe Owner,"{'name': 'Maria Lopez', 'relation_type': 'frie...","[friendly, outgoing, hospitable]",Isabella Rodriguez is a cafe owner of Hobbs Ca...,Isabella is planning a Valentine's Day party a...,"Isabella Rodriguez goes to bed around 11pm, aw...",2023-02-13 23:00,60,home:bathroom,night_routine,"running water, scent of face wash, soft towel,...",Preparing for bed after a long day.